0219 - add proposed provides property and remove subtitles
IIIF/cookbook-recipes pull request #570
Opened 2024-12-20 19:09 UTC by elynema

See issue #555 . First pass at adding the proposed  provides property to the captions recipe and removing references to subtitles. We propose to handle subtitles with a different value for the provides property in #556, so they need to be demonstrated in a different recipe.

2025-01-10 13:09 UTC, glenrobson commented
Direct link to the preview of the recipe:

https://preview.iiif.io/cookbook/update_caption_recipe/recipe/0219-using-caption-file/

2025-01-10 13:10 UTC, glenrobson commented
Changes look great. The only thing I noticed is you will have to change the title in the following file:

https://github.com/IIIF/cookbook-recipes/blob/update_caption_recipe/_includes/links.md

To update the main page at: https://preview.iiif.io/cookbook/update_caption_recipe/index.html

2025-01-14 16:18 UTC, saracarl requested changes
comments for consideration, figuring out the link is the most important bit.

2025-01-14 16:18 UTC, saracarl commented on recipe/0219-using-caption-file/index.md
>  - [Using Annotations for Timed Text][0079]
Any idea why this link isn't working on the preview site?

2025-01-14 16:18 UTC, saracarl commented on recipe/0219-using-caption-file/index.md
>  While captions, subtitles, and transcripts each present some text interpretation of the A/V content, the ways in which they are consumed by users differ. For a more detailed discussion about these di
Would we want to address `commenting` here as well?  Maybe link to that recipe?

2025-02-10 22:49 UTC, elynema commented on recipe/0219-using-caption-file/index.md
>  - [Using Annotations for Timed Text][0079]
@saracarl Which link are you referring to? I removed the link to the recipe for providing alternative representations because it didn't seem particularly relevant. I would argue that 0257 [Serving HLS Files] should be removed as well.

2025-02-10 22:50 UTC, elynema commented on recipe/0219-using-caption-file/index.md
>  While captions, subtitles, and transcripts each present some text interpretation of the A/V content, the ways in which they are consumed by users differ. For a more detailed discussion about these di
@saracarl In this particular section of the recipe, we're really only talking about captions, so I don't think `commenting` is relevant here. I could see potentially putting a link to a commenting recipe at the bottom?

2025-02-18 16:08 UTC, saracarl commented on recipe/0219-using-caption-file/index.md
>  - [Using Annotations for Timed Text][0079]
looks good -- maybe it just hadn't rebuilt?

2025-02-18 16:17 UTC, saracarl commented on recipe/0219-using-caption-file/index.md
>  While captions, subtitles, and transcripts each present some text interpretation of the A/V content, the ways in which they are consumed by users differ. For a more detailed discussion about these di
We decided to link to https://preview.iiif.io/cookbook/0103-poetry in the related recipes to "answer" this.

2026-05-19 17:39 UTC, triplingual commented
@glenrobson Does this PR need to get re-pointed to `v4` rather than the trunk?

2026-06-15 23:33 UTC, glenrobson commented
Yes, so I think we need to close this pull request and open a new one which takes the `update_caption_recipe` branch and points it to `v4`

2026-06-15 23:36 UTC, glenrobson commented
Created: https://github.com/IIIF/cookbook-recipes/pull/711

2026-06-15 23:36 UTC, closed without merging